name: Embodied End-to-End Tests

on:
  workflow_call:

jobs:
  embodied-mlp-sac-maniskill-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openvla --env maniskill_libero

      - name: ManiSkill SAC test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh maniskill_sac_mlp

      - name: ManiSkill Async SAC test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run_async.sh maniskill_sac_mlp_async

      - name: ManiSkill Async SAC test with env decoupled mode
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run_async.sh maniskill_sac_mlp_async_decoupled

      - name: ManiSkill Async SAC test with env decoupled mode and real simulator delay
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run_async.sh maniskill_sac_mlp_async_decoupled_with_delay

      - name: ManiSkill Async SAC eval test with env decoupled mode
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/evaluations/run.sh maniskill_sac_mlp_async_decoupled_eval 

      - name: ManiSkill SAC Flow State test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh maniskill_sac_flow_state

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-d4rl-offline-iql-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment (d4rl)
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --env d4rl

      - name: D4RL Offline IQL test (no FSDP wrap)
        timeout-minutes: 15
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run_offline.sh d4rl_iql_mujoco

      - name: D4RL Offline IQL test (FSDP wrap)
        timeout-minutes: 15
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run_offline.sh d4rl_iql_mujoco egl actor.use_fsdp_wrap=true

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-cnn-realworld-dummy-sac-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openvla --env maniskill_libero

      - name: ManiSkill SAC test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh realworld_dummy_sac_cnn

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-cnn-realworld-xsquare-turtle2-dummy-sac-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openvla --env maniskill_libero

      - name: Xsquare-turtle2 SAC dummy test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh realworld_xsquare_turtle2_dummy_sac_cnn

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-mlp-realworld-dosw1-dummy-sac-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --env dosw1

      - name: DOSW1 Pick SAC dummy test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh dosw1_dummy_sac_mlp_pick

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-mlp-frankasim-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export SERL_PATH=/workspace/dataset/serl
          bash requirements/install.sh embodied --model openvla --env frankasim

      - name: MLP PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh frankasim_ppo_mlp

      - name: CNN SAC test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run_async.sh frankasim_sac_cnn_async

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-mlp-ppo-genesis-cubepick-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Genesis dependencies
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --env genesis

      - name: Run Genesis CubePick PPO MLP e2e test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh genesis_cubepick_ppo_mlp

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvla-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openvla --env maniskill_libero

      - name: ManiSkill PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh maniskill_ppo_openvla

      - name: ManiSkill Async PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run_async.sh maniskill_async_ppo_openvla

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openvla-oft --env maniskill_libero

      - name: ManiSkill GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          cp -r /workspace/dataset/maniskill_assets/assets ${REPO_PATH}/rlinf/envs/maniskill/
          bash tests/e2e_tests/embodied/run.sh maniskill_grpo_openvlaoft

      - name: Libero-Goal GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_goal_grpo_openvlaoft

      - name: Libero-Spatial OPD test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_opd_openvlaoft

      - name: ManiSkill Async PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          cp -r /workspace/dataset/maniskill_assets/assets ${REPO_PATH}/rlinf/envs/maniskill/
          bash tests/e2e_tests/embodied/run_async.sh maniskill_async_ppo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-libero-rocm-test:
    runs-on: rocm
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create ROCm embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh --platform amd embodied --model openvla-oft --env libero

      - name: Libero-Goal GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_goal_grpo_openvlaoft osmesa

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openpi-maniskill-libero-musa-test:
    runs-on: musa
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create MUSA embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh --platform musa embodied --model openpi --env maniskill_libero

      - name: LIBERO-10 PPO OpenPI Pi05 test
        timeout-minutes: 60
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          export ROBOT_PLATFORM=LIBERO
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_10_ppo_openpi_pi05_musa osmesa
          ray stop

      - name: ManiSkill PPO OpenPI Pi05 test
        timeout-minutes: 60
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          export ROBOT_PLATFORM=BRIDGE
          source .venv/bin/activate
          cp -r /workspace/dataset/maniskill_assets/assets ${REPO_PATH}/rlinf/envs/maniskill/
          bash tests/e2e_tests/embodied/run.sh maniskill_async_ppo_openpi_pi05_musa osmesa
          ray stop

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-libero-ascend-test:
    runs-on: ascend
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create Ascend embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh --platform ascend embodied --model openvla-oft --env libero

      - name: Libero-Goal GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_goal_grpo_openvlaoft osmesa
          ray stop

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-behavior-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export BEHAVIOR_PATH=/workspace/dataset/BEHAVIOR-1K
          export ISAAC_SIM_WHEEL_PATH=/workspace/dataset/isaac_sim_wheels
          bash requirements/install.sh embodied --model openvla-oft --env behavior

      - name: BEHAVIOR-OpenVLA-OFT test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export OMNIGIBSON_DATA_PATH=/workspace/dataset/behavior-datasets
          export ISAAC_PATH=/workspace/dataset/isaac-sim
          bash tests/e2e_tests/embodied/run.sh behavior_ppo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
          rm -rf /tmp/tmp*

  embodied-reward-model-maniskill-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --env maniskill_libero --model qwen3_vl --torch 2.8.0 --sglang 0.5.4 --transformers 4.57.1

      - name: ManiSkill VLM Trend Reward PPO test (managed SGLang)
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh maniskill_ppo_mlp_vlm_trend_reward_sglang

      - name: ManiSkill ResNet Reward PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh maniskill_ppo_mlp_resnet_reward

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-robotwin-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openvla-oft --env robotwin

      - name: RoboTwin-OpenVLA-OFT test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export ROBOT_PLATFORM=ALOHA
          export ROBOTWIN_PATH="/workspace/dataset/RoboTwin"
          export PYTHONPATH=${ROBOTWIN_PATH}:$PYTHONPATH
          bash tests/e2e_tests/embodied/run.sh robotwin_grpo_openvlaoft

      - name: RoboTwin-OpenVLA-OFT eval test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export ROBOT_PLATFORM=ALOHA
          export ROBOTWIN_PATH="/workspace/dataset/RoboTwin"
          export PYTHONPATH=${ROBOTWIN_PATH}:$PYTHONPATH
          bash tests/e2e_tests/evaluations/run.sh robotwin_place_empty_cup_openvlaoft_eval

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openpi-behavior-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export BEHAVIOR_PATH=/workspace/dataset/BEHAVIOR-1K
          export ISAAC_SIM_WHEEL_PATH=/workspace/dataset/isaac_sim_wheels
          bash requirements/install.sh embodied --model openpi --env behavior

      - name: BEHAVIOR-OpenPI test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export OMNIGIBSON_DATA_PATH=/workspace/dataset/behavior-datasets
          export ISAAC_PATH=/workspace/dataset/isaac-sim
          bash tests/e2e_tests/embodied/run.sh behavior_ppo_openpi

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
          rm -rf /tmp/tmp*

  embodied-openpi-pytorch-behavior-eval-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export BEHAVIOR_PATH=/workspace/dataset/BEHAVIOR-1K
          export ISAAC_SIM_WHEEL_PATH=/workspace/dataset/isaac_sim_wheels
          bash requirements/install.sh embodied --model openpi --env behavior

      - name: BEHAVIOR-OpenPI-PyTorch eval test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export OMNIGIBSON_DATA_PATH=/workspace/dataset/behavior-datasets
          export ISAAC_PATH=/workspace/dataset/isaac-sim
          bash tests/e2e_tests/evaluations/run.sh behavior_openpi_rlinf_eval

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
          rm -rf /tmp/tmp*

  embodied-gr00t-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export GR00T_PATH=/workspace/dataset/Isaac-GR00T/
          bash requirements/install.sh embodied --model gr00t --env maniskill_libero

      - name: Libero-Spatial PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_ppo_gr00t

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-gr00t-libero-ascend-test:
    runs-on: ascend
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create Ascend embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export GR00T_PATH=/workspace/dataset/Isaac-GR00T/
          export DECORD_PATH=/workspace/dataset/decord
          bash requirements/install.sh --platform ascend embodied --model gr00t --env libero

      - name: Libero-Spatial PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_ppo_gr00t osmesa
          ray stop

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-gr00t-isaaclab-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export ISAAC_LAB_PATH=/workspace/dataset/IsaacLab
          export GR00T_PATH=/workspace/dataset/Isaac-GR00T/
          bash requirements/install.sh embodied --model gr00t --env isaaclab

      - name: ISAACLAB PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          source /workspace/dataset/isaac-sim-5.1/setup_conda_env.sh
          bash tests/e2e_tests/embodied/run.sh isaaclab_ppo_gr00t

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
          rm -rf /tmp/tmp*

  embodied-openpi-isaaclab-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export ISAAC_LAB_PATH=/workspace/dataset/IsaacLab
          bash requirements/install.sh embodied --model openpi --env isaaclab

      - name: ISAACLAB OpenPI PPO Pi05 test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          source /workspace/dataset/isaac-sim-5.1/setup_conda_env.sh
          bash tests/e2e_tests/embodied/run.sh isaaclab_ppo_openpi_pi05

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
          rm -rf /tmp/tmp*
          
  embodied-openpi-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openpi --env maniskill_libero

      - name: Maniskill PPO Pi05 training pipeline test
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          cp -r /workspace/dataset/maniskill_assets/assets ${REPO_PATH}/rlinf/envs/maniskill/
          bash tests/e2e_tests/embodied/run.sh maniskill_ppo_openpi05_pipeline

      - name: Libero-Spatial PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_ppo_openpi

      - name: Libero-Object NFT test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_object_nft_openpi

      - name: Libero-Spatial DAgger test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_dagger_openpi

      - name: Libero-Spatial PPO Pi05 torch compile test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_ppo_openpi05 +rollout.enable_torch_compile=true +rollout.torch_compile_mode=max-autotune

      - name: ManiSkill Async PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          cp -r /workspace/dataset/maniskill_assets/assets ${REPO_PATH}/rlinf/envs/maniskill/
          bash tests/e2e_tests/embodied/run_async.sh maniskill_async_ppo_openpi

      - name: Libero-Spatial DSRL PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_dsrl_openpi

      - name: Maniskill PPO Co-Training Pi05 test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          cp -r /workspace/dataset/RLCo-maniskill-assets/custom_assets ${REPO_PATH}/rlinf/envs/maniskill/assets
          bash tests/e2e_tests/embodied/run.sh maniskill_ppo_co_training_openpi_pi05

      - name: ManiSkill RLT Stage2 AC MLP test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          cp -r /workspace/dataset/maniskill_assets/assets ${REPO_PATH}/rlinf/envs/maniskill/
          bash tests/e2e_tests/embodied/run.sh maniskill_rlt_stage2_ac_mlp

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openpi-maniskill-gsenv-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openpi --env maniskill_libero

          source .venv/bin/activate
          cd /workspace/dataset/ManiSkill-GS
          uv pip install -e .
          python scripts/test_rlinf_interface.py

      - name: ManiSkill-GS PPO Pi05 test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh gsenv_ppo_openpi_pi05

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openpi-metaworld-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openpi --env metaworld

      - name: Metaworld PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh metaworld_50_ppo_openpi

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-metaworld-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openvla-oft --env metaworld

      - name: Metaworld PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh metaworld_50_ppo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openpi-calvin-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export CALVIN_PATH=/workspace/dataset/calvin
          bash requirements/install.sh embodied --model openpi --env calvin

      - name: Calvin PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh calvin_ppo_openpi

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-calvin-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export CALVIN_PATH=/workspace/dataset/calvin
          bash requirements/install.sh embodied --model openvla-oft --env calvin

      - name: Calvin PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh calvin_ppo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openpi-robocasa-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export ROBOCASA_PATH=/workspace/dataset/robocasa
          bash requirements/install.sh embodied --model openpi --env robocasa

      - name: Robocasa PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh robocasa_closedrawer_ppo_openpi

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openpi-roboverse-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openpi --env roboverse

      - name: RoboVerse PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          cp -r /workspace/dataset/roboverse_data .
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh roboverse_ppo_openpi_pi05
          mv roboverse_data .venv/roboverse/

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openpi-robocasa365-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export ROBOCASA_PATH=/workspace/dataset/robocasa365
          export ROBOCASA_ASSETS_PATH=/workspace/dataset/robocasa365_assets
          bash requirements/install.sh embodied --model openpi --env robocasa365

      - name: RoboCasa365 PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          export ROBOCASA_PATH=/workspace/dataset/robocasa365
          export ROBOCASA_ASSETS_PATH=/workspace/dataset/robocasa365_assets
          export ROBOCASA365_OPENPI_CKPT=/workspace/dataset/pi0-robocasa-pretrain-human300
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh robocasa365_ppo_openpi

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-dexbotic-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export DEXBOTIC_PATH=/workspace/dataset/dexbotic
          bash requirements/install.sh embodied --model dexbotic --env maniskill_libero

      - name: Libero-Spatial PPO Dexbotic test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_ppo_dexbotic_pi0

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-starvla-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export STARVLA_PATH=/workspace/dataset/starVLA
          bash requirements/install.sh embodied --model starvla --env maniskill_libero

      - name: Libero-10 GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_10_grpo_starvla

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-opensora-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export OPENSORA_PATH=/workspace/dataset/opensora
          bash requirements/install.sh embodied --model openvla-oft --env opensora

      - name: OpenSora GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh opensora_libero_spatial_grpo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-wan-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export WAN_PATH=/workspace/dataset/wan
          bash requirements/install.sh embodied --model openvla-oft --env wan

      - name: Wan GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh wan_libero_spatial_grpo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-lingbotvla-robotwin-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export ROBOTWIN_PATH=/workspace/dataset/RoboTwin
          export LINGBOT_PATH=/workspace/dataset/lingbot-vla
          bash requirements/install.sh embodied --model lingbotvla --env robotwin

      - name: RoboTwin-LingBotVLA GRPO test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export ROBOT_PLATFORM=ALOHA
          export ROBOTWIN_PATH="/workspace/dataset/RoboTwin"
          export PYTHONPATH=${ROBOTWIN_PATH}:$PYTHONPATH
          export LINGBOT_VLA_PATH="/workspace/dataset/lingbot-vla"
          bash tests/e2e_tests/embodied/run.sh robotwin_grpo_lingbotvla

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-liberopro-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PRO_PATH=/workspace/dataset/LIBERO-PRO
          bash requirements/install.sh embodied --model openvla-oft --env liberopro

      - name: LIBERO-Pro GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export LIBERO_TYPE=pro
          bash tests/e2e_tests/embodied/run.sh liberopro_10_grpo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-liberoplus-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PLUS_PATH=/workspace/dataset/LIBERO-PLUS
          bash requirements/install.sh embodied --model openvla-oft --env liberoplus

      - name: LIBERO-Plus GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export LIBERO_TYPE=plus
          bash tests/e2e_tests/embodied/run.sh liberoplus_10_grpo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-evo1-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export EVO1_PATH=/workspace/dataset/Evo-1
          bash requirements/install.sh embodied --model evo1 --env libero

      - name: LIBERO Evo-1 GRPO test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export ROBOT_PLATFORM=LIBERO
          export LIBERO_TYPE=standard
          bash tests/e2e_tests/embodied/run.sh libero_spatial_grpo_evo1

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-abot-m0-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model abot_m0 --env maniskill_libero

      - name: Patch ABot-M0 VGGT path
        run: |
          source .venv/bin/activate
          ABOT_PATH=$(python -c "import ABot; import os; print(os.path.dirname(ABot.__file__))")
          sed -i "s|VGGT.from_pretrained('facebook/VGGT-1B')|VGGT.from_pretrained('/workspace/dataset/VGGT-1B')|" \
            "${ABOT_PATH}/model/framework/ABot_M0.py"

      - name: LIBERO ABot-M0 PPO test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export LIBERO_TYPE=standard
          bash tests/e2e_tests/embodied/run.sh libero_10_ppo_abot_m0

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-abot-m0-liberoplus-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PLUS_PATH=/workspace/dataset/LIBERO-PLUS
          bash requirements/install.sh embodied --model abot_m0 --env liberoplus

      - name: Patch ABot-M0 VGGT path
        run: |
          source .venv/bin/activate
          ABOT_PATH=$(python -c "import ABot; import os; print(os.path.dirname(ABot.__file__))")
          sed -i "s|VGGT.from_pretrained('facebook/VGGT-1B')|VGGT.from_pretrained('/workspace/dataset/VGGT-1B')|" \
            "${ABOT_PATH}/model/framework/ABot_M0.py"

      - name: LIBERO-Plus ABot-M0 PPO test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export LIBERO_TYPE=plus
          bash tests/e2e_tests/embodied/run.sh liberoplus_10_ppo_abot_m0

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-embodichain-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --env embodichain

      - name: EmbodiChain CartPole PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export LD_LIBRARY_PATH="$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))'):${LD_LIBRARY_PATH:-}"
          export EMBODICHAIN_DATA_ROOT=/workspace/dataset/embodichain_data
          python -m embodichain.data download --name CartPole
          python -m embodichain.data download --name SimResources
          bash tests/e2e_tests/embodied/run.sh embodichain_ppo_cart_pole

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-gr00t_n1d6-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export GR00T_PATH=/workspace/dataset/Isaac-GR00T-1.6/
          bash requirements/install.sh embodied --model gr00t_n1d6 --env maniskill_libero

      - name: Libero-Spatial PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_ppo_gr00t_n1d6

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-gr00t_n1d7-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export GR00T_PATH=/workspace/dataset/Isaac-GR00T-1.7/
          bash requirements/install.sh embodied --model gr00t_n1d7 --env maniskill_libero

      - name: Libero-Spatial PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_ppo_gr00t_n1d7

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openpi-polaris-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export POLARIS_PATH=/workspace/dataset/polaris
          bash requirements/install.sh embodied --model openpi --env polaris

      - name: PolaRiS PPO OpenPI Pi05 test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export POLARIS_DATA_PATH=/workspace/dataset/PolaRiS-Hub
          source /workspace/dataset/isaac-sim-5.1/setup_conda_env.sh
          bash tests/e2e_tests/embodied/run.sh polaris_tapeintocontainer_ppo_openpi_pi05

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-molmoact2-libero-eval-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export MOLMOACT2_LEROBOT_PATH=/workspace/dataset/lerobot-molmoact2
          bash requirements/install.sh embodied --model molmoact2 --env libero

      - name: LIBERO MolmoAct2 evaluation test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export ROBOT_PLATFORM=LIBERO
          export LIBERO_TYPE=standard
          bash tests/e2e_tests/embodied/run_eval.sh libero_10_molmoact2_eval

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
